import './relay.css';
import {runActivity} from './relay-activities.js';
import {RELAY_STEPS,relayStepIndex,relayProgress,relayConnection} from './relay-story.js';
import {RelayScene} from './relay-scene.js';
import {CHAPTERS,MEALS,PROGRAMS,TRANSPORTS,POPUP_ITEMS,createRelayState,relayReducer,restoreRelayState,canEnter,nextAction,minutesAt,clockLabel} from './relay-model.js';
import research from '../public/data/relay-research.json';
import photos from '../public/data/relay-media.json';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>n.toLocaleString('ko-KR')+'원';
const icon=(name,size=20)=>{
 const paths={arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5ZM9 3v16m6-14v16"/>',photo:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/>',ticket:'<path d="M3 6h18v4a2 2 0 0 0 0 4v4H3v-4a2 2 0 0 0 0-4V6Zm12 0v12"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',reset:'<path d="M3 10a9 9 0 1 1 2 9M3 4v6h6"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/>',pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',hand:'<path d="M8 12V5a2 2 0 0 1 4 0v7-8a2 2 0 0 1 4 0v8-5a2 2 0 0 1 4 0v9c0 4-3 6-7 6-2 0-4-1-5-3l-5-7a2 2 0 0 1 3-2l2 2Z"/>'};
 return `<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.arrow}</svg>`;
};
const photoById=id=>photos.find(p=>p.id===id);
function routeSVG(stage){const coords=research.route.coordinates;const xs=coords.map(c=>c[0]),ys=coords.map(c=>c[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const to=c=>[24+(c[0]-minX)/(maxX-minX)*268,86-(c[1]-minY)/(maxY-minY)*62];const path=coords.map(c=>to(c).join(',')).join(' ');const idx=stage<=3?0:stage===4?Math.floor(coords.length*.45):coords.length-1;const [x,y]=to(coords[idx]);return `<svg viewBox="0 0 318 112" role="img" aria-label="원도심에서 월영교로 이어지는 약 ${(research.route.distanceMeters/1000).toFixed(1)}km 설명 경로"><path d="M180 0C150 50 246 61 220 120" fill="none" stroke="#7caba1" stroke-opacity=".25" stroke-width="25"/><polyline points="${path}" fill="none" stroke="#d7b779" stroke-width="2.4" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r="5" fill="#edce90" stroke="#283f38" stroke-width="3"/><text x="14" y="108">원도심</text><text x="238" y="17">월영교</text></svg>`;}
export async function initRelay(){
 document.title='안동 이어드림 · 한 끼에서 안동의 밤까지';
 document.body.className='relay-body';
 let state=createRelayState();try{const saved=localStorage.getItem('andong-relay-v1');if(saved)state=restoreRelayState(saved);}catch{}
 let preview=null,contextOpen=false,busy=false,scene=null,sceneKey='',aim=50,lowQuality=false,drawerOpener=null;
 const app=document.createElement('div');app.className='relay-app';document.body.replaceChildren(app);
 app.innerHTML=`<main id="relay-world" aria-label="이어드림 1인칭 여행"></main><div class="relay-shade" aria-hidden="true"></div>
 <header class="relay-header"><a class="relay-brand" href="/" aria-label="기존 지도 첫 화면으로 돌아가기"><span class="brand-symbol">이</span><span>안동 이어드림<small>ANDONG · EODREAM</small></span></a><span class="relay-header-tag">식음·체험 <i>→</i> 저녁 이동 <i>→</i> 야간 체류</span><div class="relay-header-actions"><button id="relay-sources" aria-label="실제 사진과 조사 자료">${icon('photo')}<span>사진·현장 정보</span></button><a href="?layout=atlas" id="relay-atlas">${icon('map')}<span>전체 지도</span></a><button id="relay-settings" aria-label="화면 설정">${icon('sun')}</button></div></header>
 <nav class="relay-flow-nav" aria-label="릴레이 진행 단계" hidden></nav>
 <section class="relay-welcome" aria-labelledby="relay-welcome-title"><p class="relay-overline">한 사람의 여행으로 이어지는 릴레이</p><h1 id="relay-welcome-title">한 끼에서,<br>안동의 <em>밤</em>까지.</h1><p class="welcome-description">식사 영수증이 체험 혜택으로, 원도심의 체험이 월영교의 밤으로.<br>이 연결을 관광객의 눈으로 직접 경험해보세요.</p><button class="relay-primary" id="relay-start">${state.started?'릴레이 이어서 체험하기':'릴레이 직접 체험하기'} ${icon('arrow')}</button><div class="welcome-meta"><span>${icon('hand',16)} 직접 조작하는 3D 여행</span><span>혜택을 받고, 만들고, 이동하고, 머물러요</span></div></section>
 <aside class="relay-overview" aria-label="오늘 체험할 여정"><span class="relay-overline">이어드림이 연결하는 세 단계</span><h2>한 번의 방문을<br>하루의 경험으로</h2><div id="relay-overview-stops"></div><p>하나의 영수증에서 시작한 경험이<br>안동의 밤까지 이어집니다.</p></aside>
 <section class="relay-scene-copy" hidden><p class="relay-overline" id="relay-kicker"></p><h1 id="relay-title" tabindex="-1"></h1><p id="relay-subtitle"></p><div class="relay-location">${icon('pin',15)} <span id="relay-location"></span></div><button class="relay-text-button" id="relay-source-context">실제 사진과 조사한 정보 ${icon('arrow',15)}</button></section>
 <div class="relay-reticle" aria-hidden="true"></div><button id="relay-interact" class="relay-world-interact" hidden><kbd>E</kbd><span></span></button><div id="relay-paint-task" class="relay-paint-task" hidden><strong>탈 위에서 누른 채 붓을 움직여보세요</strong><p>색을 칠할수록 진행됩니다. 터치로도 칠할 수 있어요.</p><progress max="1" value="0" aria-label="탈 색칠 진행률"></progress><div><button id="relay-paint-assist">색칠 동작 도움받기</button><button id="relay-paint-cancel">돌아가기</button></div></div><div id="relay-dialogue" class="relay-dialogue" hidden></div><div class="relay-look-hint">${icon('hand',16)} 드래그로 둘러보기 <span>· W A S D 이동 · Shift 빠르게 · E 상호작용</span></div>
 <section class="relay-route-mini" hidden aria-label="여정 지도"><div><span id="relay-time"></span><button id="relay-route-open">동선·교통 정보 ${icon('arrow',13)}</button></div><div id="relay-mini-map"></div><p>공개 도로망 설명 경로 · 시각은 시연 가정</p></section>
 <section class="relay-control" hidden aria-label="현재 장면에서 할 일"><button id="relay-panel-toggle" class="relay-panel-toggle" aria-expanded="false">메뉴·체험 선택 펼치기 <span>＋</span></button><div id="relay-preview-note" hidden>장면 미리보기 · 진행 기록은 유지됩니다</div><div id="relay-context"></div><div id="relay-connection" class="relay-connection" aria-live="polite"></div><button class="relay-primary" id="relay-action"></button><p id="relay-action-note"></p></section>
 <div class="relay-mobile-look" hidden><button data-look=".22" aria-label="왼쪽 둘러보기">←</button><button id="relay-forward" aria-label="앞으로 이동">↑</button><button id="relay-backward" aria-label="뒤로 이동">↓</button><button data-look="-.22" aria-label="오른쪽 둘러보기">→</button></div>
 <footer class="relay-footer"><span class="relay-proposal-note"><i></i> 이어드림 사업 제안 시뮬레이션</span><span class="relay-footer-center">공간은 재구성 · 인증과 구매는 시연</span><div><button id="relay-mobile-route" aria-label="동선과 교통 정보">${icon('map',17)}</button><button id="relay-wallet">${icon('ticket',17)}<span id="relay-wallet-label">나의 여행 기록</span></button><button id="relay-reset" aria-label="여정 처음부터">${icon('reset',17)}</button></div></footer>
 <p class="relay-toast" id="relay-status" role="status" aria-live="polite"></p>
 <dialog id="relay-drawer" class="relay-drawer"><div class="drawer-heading"><h2 id="relay-drawer-title"></h2><button id="relay-drawer-close" aria-label="정보 닫기">${icon('close')}</button></div><div id="relay-drawer-content"></div></dialog>
 <dialog id="relay-summary" class="relay-summary"><button class="summary-close" id="relay-summary-close" aria-label="완주 기록 닫기">${icon('close')}</button><div id="relay-summary-content"></div></dialog>`;
 document.documentElement.classList.remove('relay-loading');
 const $=id=>document.getElementById(id);
 const flowHTML=(steps,{live=false,previewing=false}={})=>steps.map((step,n)=>`<button data-chapter="${step.stage}" class="flow-step ${live&&step.completed?'flow-completed':''}" ${live&&step.current?'aria-current="step"':''}><b>${live&&step.completed?'✓':String(n+1).padStart(2,'0')}</b><span>${step.label}${live?`<small>${previewing&&step.current?'장면 미리보기':step.current?'지금 체험 중':step.completed?'연결 완료':step.detail}</small>`:''}</span></button>${n<steps.length-1?'<span class="flow-arrow" aria-hidden="true">→</span>':''}`).join('');
 $('relay-overview-stops').innerHTML=[{i:0,title:'식음·체험 릴레이',text:'식사 → 영수증 인증 → 체험 혜택'},{i:4,title:'저녁 이동 연결',text:'원도심의 체험을 월영교로 연결'},{i:5,title:'월영교 야간 체류',text:'야경 산책 → 음식·공예·놀이 팝업'}].map((c,n)=>`<button data-chapter="${c.i}"><b>0${n+1}</b><span>${c.title}<small>${c.text}</small></span>${icon('arrow',16)}</button>`).join('');
 let toastTimer;
 function announce(text){$('relay-status').textContent=text;$('relay-status').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('relay-status').classList.remove('show'),4500);}
 function persist(){try{localStorage.setItem('andong-relay-v1',JSON.stringify(state));}catch{}}
 function dispatch(action){state=relayReducer(state,action);persist();render();}
 function displayed(){return preview===null?state:{...state,stage:preview,started:true};}
 function openDrawer(title,html){drawerOpener=document.activeElement;$('relay-drawer-title').textContent=title;$('relay-drawer-content').innerHTML=html;if(!$('relay-drawer').open)$('relay-drawer').showModal();scene?.setPaused(true);$('relay-drawer-content').scrollTop=0;}
 function closeDrawer(){$('relay-drawer').close();scene?.setPaused(false);drawerOpener?.focus?.({preventScroll:true});}
 $('relay-drawer-close').onclick=closeDrawer;$('relay-drawer').addEventListener('cancel',()=>scene?.setPaused(false));
 $('relay-drawer').addEventListener('click',e=>{if(e.target===$('relay-drawer')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDrawer();}});
 function photoHTML(p){if(!p)return '';return `<figure class="reference-photo">${p.local?`<img loading="lazy" src="${esc(p.local)}" alt="${esc(p.caption)}">`:'<div class="photo-unavailable">사진 제공 서버에 연결되지 않아 원문 링크로 안내합니다.</div>'}<figcaption><strong>${esc(p.caption)}</strong><span>${esc(p.credit)} · <a target="_blank" rel="noopener" href="${esc(p.licenseUrl)}">${esc(p.license)}</a></span><span>촬영 ${esc(p.capturedAt||'미확인')} · ${p.local?'원본 전체 표시':'이미지 미수집'}</span><a target="_blank" rel="noopener" href="${esc(p.sourceUrl)}">사진 출처 보기 ↗</a></figcaption></figure>`;}
 function showSources(){
  const d=displayed(),stage=CHAPTERS[d.stage];const ids=research.chapters[stage.id]||[];
  const mediaIds=stage.id==='workshop'?d.program==='tea'?['tea','hahoe']:d.program==='soju'?['soju','hahoe']:['mask','hahoe']:['market','meal','receipt'].includes(stage.id)?['jjimdak','tour-2866691','tour-2679452','tour-134770']:stage.id==='popup'?['maskdance','moon','mask']:stage.id==='transit'?['moon']:['moon'];
  openDrawer('사진과 현장 정보',`<p class="drawer-intro">${esc(stage.location)}<br><small>확인일 ${research.checkedAt} · 실내·부스는 기획을 설명하기 위해 재구성했습니다.</small></p><div class="reference-gallery">${mediaIds.map(id=>photoHTML(photoById(id))).join('')}</div><h3>이 장면의 확인 자료</h3>${research.sources.filter(s=>ids.includes(s.id)).map(sourceHTML).join('')}<details><summary>전체 조사 자료 ${research.sources.length}곳</summary>${research.sources.filter(s=>!ids.includes(s.id)).map(sourceHTML).join('')}</details><details><summary>현재 확인하지 못한 항목</summary><ul>${research.unknowns.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`);
 }
 function sourceHTML(s){return `<article class="source-record"><span>${esc(s.status)}</span><h4>${esc(s.title)}</h4><ul>${s.facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><a href="${esc(s.url)}" target="_blank" rel="noopener">원문 확인 ↗</a><small>확인 ${esc(s.checkedAt)}</small></article>`;}
 function showRoute(){const distance=(research.route.distanceMeters/1000).toFixed(1);openDrawer('저녁을 잇는 동선',`<div class="route-drawer-map">${routeSVG(displayed().stage)}</div><p class="drawer-intro">원도심 → 체험 거점 → 월영교 · 약 ${distance}km</p><p>지도 선은 기존 공개 도로망에서 만든 거점 간 설명 경로입니다. 실제 버스 노선이나 최적 도보 길찾기는 아닙니다.</p><ol class="route-timeline">${CHAPTERS.map((c,i)=>`<li><time>${clockLabel(minutesAt({...state,stage:i}))}</time><span>${esc(c.location)}</span></li>`).join('')}</ol><p class="small-note">출발 17:00 · 체류·이동 시간은 시연 가정이며 실제 예약 일정이 아닙니다.</p><h3>이동 수단</h3>${Object.values(TRANSPORTS).map(t=>`<article class="source-record"><h4>${t.name}</h4><p>${t.note}</p></article>`).join('')}${sourceHTML(research.sources.find(x=>x.id==='transport'))}${sourceHTML(research.sources.find(x=>x.id==='parking'))}<a class="drawer-link" href="?layout=journey">기존 지도에서 코스·귀가편 살펴보기 ${icon('arrow')}</a>`);}
 function walletHTML(){const program=PROGRAMS[state.redeemedProgram||state.program];return `<div class="wallet-ticket"><span>이어드림 · 체험 할인권</span><strong>10<em>%</em></strong><p>${state.coupon==='used'?'사용 완료':state.coupon==='issued'?'발급 완료 · 체험장에서 사용':'식사 후 영수증을 인증하세요'}</p><small>제안 혜택 · 실제 가맹점에서 사용할 수 없음</small></div><ul class="journal-list"><li><span>식사</span><b>${state.eaten?MEALS[state.meal].name+' · 완료':'아직 이용 전'}</b></li><li><span>인증</span><b>${state.receipt==='verified'?'시연 영수증 인증 완료':'대기'}</b></li><li><span>체험</span><b>${state.completedPrograms.length?state.completedPrograms.map(p=>PROGRAMS[p].short).join(' · '):'아직 체험 전'}</b></li><li><span>이동</span><b>${state.arrived?TRANSPORTS[state.transport].name:'아직 이동 전'}</b></li><li><span>야경</span><b>${state.bridgeWalked?'월영정 산책 완료':'아직 산책 전'}</b></li><li><span>팝업</span><b>${state.cart.length?state.cart.map(p=>POPUP_ITEMS[p].name).join(' · '):'구매 시연 전'}</b></li><li><span>투호</span><b>${state.gameScore} / ${state.gameAttempts} 성공</b></li></ul>${state.coupon==='used'?`<div class="journal-cost"><span>${program.name} · 할인 계산 예시</span><p><del>${money(program.examplePrice)}</del> → <strong>${money(program.examplePrice*.9)}</strong></p><small>예시 기준 ${money(program.examplePrice*.1)} 할인. 이 거점의 실제 판매가격은 미확정입니다.</small></div>`:''}${state.maskArt?`<a class="drawer-link" href="${esc(state.maskArt)}" download="내가-칠한-안동탈.png">내가 칠한 탈의 색칠 기록 저장하기 ↗</a>`:''}<p class="small-note">개인정보·실제 영수증을 수집하지 않습니다. 이 브라우저에 시연 진행 기록만 저장합니다. QR 인증은 디지털 관광주민증 실적과 별개입니다.</p>`;}
 $('relay-wallet').onclick=()=>openDrawer('나의 여행 기록',walletHTML());$('relay-sources').onclick=showSources;$('relay-source-context').onclick=showSources;$('relay-route-open').onclick=showRoute;$('relay-mobile-route').onclick=showRoute;
 $('relay-reset').onclick=()=>{openDrawer('여정을 처음부터',`<p class="drawer-intro">식사·쿠폰·체험·팝업 시연 기록을 초기화합니다.</p><button class="relay-primary" id="relay-confirm-reset">처음부터 다시 체험 ${icon('reset')}</button><p class="small-note">실제 지도와 보고서 데이터에는 영향을 주지 않습니다.</p>`);$('relay-confirm-reset').onclick=()=>{closeDrawer();preview=null;sceneKey='';dispatch({type:'RESET'});$('relay-start').textContent='릴레이 직접 체험하기 →';announce('시연 기록을 초기화했습니다.');};};
 $('relay-settings').onclick=()=>{openDrawer('화면과 조작',`<p class="drawer-intro">드래그 또는 방향키로 시선을 움직여보세요.<br>3D 공간을 누른 뒤 W A S D로 이동할 수 있습니다.</p><div class="settings-options"><label><span>움직임 최소화<small>이동과 손동작을 짧게 표시합니다.</small></span><input type="checkbox" id="relay-reduce" ${scene?.reduced?'checked':''}></label><label><span>가볍게 보기<small>화면 해상도와 그림자를 줄입니다.</small></span><input type="checkbox" id="relay-low" ${lowQuality?'checked':''}></label></div><button id="relay-view-reset" class="drawer-link">시점을 원래대로 ${icon('reset')}</button><p class="small-note">E: 현재 행동 · R: 시점 복원 · 긴 이동은 건너뛰기 가능</p>`);$('relay-reduce').onchange=e=>{if(scene)scene.reduced=e.target.checked;};$('relay-low').onchange=e=>{lowQuality=e.target.checked;scene?.setQuality(lowQuality);};$('relay-view-reset').onclick=()=>{scene?.resetView();closeDrawer();};};
 $('relay-panel-toggle').onclick=()=>{contextOpen=!contextOpen;app.classList.toggle('context-open',contextOpen);$('relay-panel-toggle').setAttribute('aria-expanded',String(contextOpen));};
 $('relay-interact').onclick=()=>scene?.interact();
 function talk(role){const messages={guide:['골목 안내인','안동구시장에 오셨어요. 앞쪽 이어드림 식당으로 걸어가 간판을 바라보고 E를 눌러보세요. 식사 영수증이 다음 체험을 이어줍니다.'],host:['식당 직원',state.eaten?'식사는 어떠셨어요? 영수증을 챙겨서 QR을 직접 맞춰보세요. 발급받은 할인권은 체험장에서 사용할 수 있어요.':'어서 오세요. 찜닭, 간고등어, 헛제사밥 중 골라보세요. 메뉴를 고른 뒤 상 위의 음식을 눌러 직접 맛볼 수 있어요.'],teacher:['체험 선생님','할인권을 사용하고 원하는 체험을 골라보세요. 탈은 붓으로 직접 칠하고, 차는 알맞은 양을 따르는 게 중요해요. 다른 체험으로 옮겨도 작업은 남아있어요.'],vendor:['장터 운영자','안동의 맛과 작은 공예품이 있는 장터예요. 부스 앞으로 걸어와 물건을 눌러보세요. 옆에서는 투호도 할 수 있어요.']};const [name,message]=messages[role]||messages.vendor;$('relay-dialogue').innerHTML=`<small>등장인물 · 시연</small><strong>${name}</strong><p>${message}</p><button id="relay-talk-close">알겠어요 →</button>`;$('relay-dialogue').hidden=false;$('relay-talk-close').onclick=()=>{$('relay-dialogue').hidden=true;scene?.renderer.domElement.focus();};}
 async function paintInWorld(){if(!scene)return runActivity({type:'CRAFT',program:'mask',step:state.craftSteps,color:state.paintColor});$('relay-paint-task').hidden=false;app.classList.add('painting-mask');$('relay-paint-task').querySelector('progress').value=0;$('relay-paint-assist').onclick=()=>scene.cancelPaint(true);$('relay-paint-cancel').onclick=()=>scene.cancelPaint(false);const result=await scene.paintTask({color:state.paintColor,step:state.craftSteps,onProgress:p=>{$('relay-paint-task').querySelector('progress').value=p;}});$('relay-paint-task').hidden=true;app.classList.remove('painting-mask');if(result){const artwork=scene.maskArtwork();if(artwork)state=relayReducer(state,{type:'ART',image:artwork});}return result;}
 function contextHTML(d){
  const disabled=busy||preview!==null;
  if(d.stage===0)return `<p class="control-kicker">첫 번째 방문</p><h2>안동구시장 찜닭골목</h2><p>골목을 둘러본 뒤 식당 안으로 들어가요. 메뉴와 실용 정보는 사진·현장 정보에서 확인할 수 있어요.</p><div class="context-facts"><span>식당 내부 재구성</span><span>식사 45분 가정</span></div>`;
  if(d.stage===1)return `<p class="control-kicker">오늘의 메뉴</p><div class="meal-options">${Object.entries(MEALS).map(([id,m])=>`<button data-meal="${id}" aria-pressed="${d.meal===id}" ${disabled||d.eaten?'disabled':''}><b>${m.name}</b><small>${m.detail}</small>${d.meal===id?icon('check',16):''}</button>`).join('')}</div><p class="context-small">${d.eaten?'맛있게 먹었습니다. 계산대에서 영수증을 받아보세요.':'메뉴 가격은 현장 확인이 필요합니다. 이 식당은 기획 시연용 공간입니다.'}</p>`;
  if(d.stage===2)return `<div class="phone-ui ${busy?'scanning':''}"><div class="phone-top">이어드림 <span>영수증 인증</span></div>${d.coupon==='none'?`<div class="scan-frame"><div class="demo-qr" aria-hidden="true">${Array.from({length:81},(_,i)=>`<i style="opacity:${(i*3+Math.floor(i/9)*7)%5<3?1:0}"></i>`).join('')}</div><span class="scan-line"></span></div><strong>${d.scanError?'인식하지 못했어요':'QR을 화면 가운데 놓아주세요'}</strong><p>${d.scanError?'영수증을 밝은 곳에 놓고 다시 스캔하세요.':'개인정보 없는 샘플 영수증으로 체험합니다.'}</p>`:`<div class="coupon-success">${icon('check',24)}<strong>체험 10% 할인권</strong><p>${d.coupon==='used'?'이미 사용한 할인권입니다.':'발급 완료 · 다음 체험에서 사용하세요.'}</p></div>`}<small>ED-DEMO-001 · 시연 전용</small></div>${d.coupon==='none'?`<button class="relay-inline" id="relay-scan-fail" ${disabled?'disabled':''}>흐린 영수증으로 인식 실패 체험</button>`:''}`;
  if(d.stage===3){const p=PROGRAMS[d.program];return `<p class="control-kicker">내가 고르는 전통 체험</p><div class="program-tabs">${Object.entries(PROGRAMS).map(([id,p])=>`<button data-program="${id}" aria-pressed="${d.program===id}" ${disabled?'disabled':''}>${p.short}${d.completedPrograms.includes(id)?' ✓':''}</button>`).join('')}</div><h2>${p.name}</h2><p>${p.description}</p>${d.coupon==='issued'?`<div class="price-example"><span>시연 가격 예시 · 10% 적용</span><b><del>${money(p.examplePrice)}</del> ${money(p.examplePrice*.9)}</b></div>`:`<ol class="craft-steps">${p.steps.map((x,i)=>`<li class="${d.craftSteps>i?'done':d.craftSteps===i?'current':''}"><span>${d.craftSteps>i?'✓':i+1}</span>${x}</li>`).join('')}</ol>`}${d.program==='mask'?`<div class="paint-colors" aria-label="탈 바탕색">${['#c77a48','#d9b661','#4a8274','#bd5b4b'].map((c,i)=>`<button data-color="${c}" aria-label="${['나무빛','국화빛','청록','다홍'][i]}" aria-pressed="${d.paintColor===c}" style="--paint:${c}" ${disabled?'disabled':''}></button>`).join('')}<span>탈 바탕색</span></div>`:''}<details class="program-reality"><summary>실제 운영과 시연의 차이</summary><p>${p.reality}</p><p>회차 정원·현재 예약 가능일·휴무는 확인 필요. 체험 10% 할인은 제안입니다.</p></details>`;}
  if(d.stage===4)return `<p class="control-kicker">원도심에서 월영교까지</p><h2>저녁 이동을 선택하세요</h2><div class="transport-options">${Object.entries(TRANSPORTS).map(([id,t])=>`<button data-transport="${id}" aria-pressed="${d.transport===id}" ${disabled||d.arrived?'disabled':''}><b>${t.name}</b><span>${t.minutes}분 가정</span></button>`).join('')}</div><p class="context-small">${TRANSPORTS[d.transport].note}</p><button class="relay-inline" id="relay-transit-source">실제 버스 시간표·택시·주차 정보 ↗</button>`;
  if(d.stage===5)return `<p class="control-kicker">월영교의 밤</p><h2>강 위에 남은 달빛</h2><p>난간 너머 문보트와 황포돛배를 둘러보고 월영정으로 걸어보세요.</p><div class="bridge-options"><button id="relay-fountain" ${disabled?'disabled':''}>분수 연출 켜기 / 끄기</button><button id="relay-bridge-info">방문·운항 정보</button></div><p class="context-small">분수·조명·배는 풍경 연출입니다. 실제 가동·운항 시간과 요금은 현장 확인이 필요합니다.</p>`;
  return `<p class="control-kicker">월영교 야간 팝업 · 제안</p><h2>둘러보고, 하나 더 즐기기</h2><div class="popup-products">${Object.entries(POPUP_ITEMS).map(([id,p])=>`<button data-buy="${id}" ${disabled||d.cart.includes(id)?'disabled':''}><span><b>${p.name}</b><small>${d.cart.includes(id)?'구매 시연 완료':money(p.examplePrice)+' · 예시'}</small></span>${icon(d.cart.includes(id)?'check':'arrow',16)}</button>`).join('')}</div><div class="tuho-game"><label for="relay-aim">투호 놀이 <span>${d.gameScore}성공 / ${d.gameAttempts}회</span></label><input id="relay-aim" type="range" min="0" max="100" value="${aim}" aria-label="투호 조준" ${disabled||d.gameAttempts>=3?'disabled':''}><small>가운데 표적에 조준하세요 · 남은 기회 ${3-d.gameAttempts}회</small><button id="relay-throw" ${disabled||d.gameAttempts>=3?'disabled':''}>${d.gameAttempts>=3?'놀이 완료':'화살 던지기'}</button></div>`;
 }
 function render(){
  const d=displayed(),live=state.started||preview!==null,c=CHAPTERS[d.stage];app.dataset.stage=c.id;app.classList.toggle('tour-live',live);app.classList.toggle('tour-busy',busy);app.classList.toggle('context-open',contextOpen||preview!==null);$('relay-panel-toggle').setAttribute('aria-expanded',String(contextOpen||preview!==null));$('relay-dialogue').hidden=true;
  document.querySelector('.relay-flow-nav').hidden=!live;document.querySelector('.relay-flow-nav').innerHTML=flowHTML(relayProgress(state,d.stage),{live:true,previewing:preview!==null});document.querySelector('.relay-welcome').hidden=live;document.querySelector('.relay-overview').hidden=live;document.querySelector('.relay-scene-copy').hidden=!live;document.querySelector('.relay-control').hidden=!live;document.querySelector('.relay-route-mini').hidden=!live;document.querySelector('.relay-mobile-look').hidden=!live;
  $('relay-kicker').textContent=c.kicker;$('relay-title').textContent=c.title;$('relay-subtitle').textContent=c.subtitle;$('relay-location').textContent=c.location;
  const connection=relayConnection(d);$('relay-connection').innerHTML=`<strong>${esc(connection.title)}</strong><p>${esc(connection.text)}</p>`;$('relay-preview-note').hidden=preview===null;$('relay-context').innerHTML=contextHTML(d);const action=nextAction(d);
  $('relay-action').innerHTML=busy?`장면 체험 중… <span class="button-progress"></span>`:preview!==null?`내 여정으로 돌아가기 ${icon('arrow')}`:`${esc(action.label)} ${icon('arrow')}`;
  $('relay-action').disabled=busy||(preview===null&&!!action.disabled);
  $('relay-action-note').innerHTML=busy?'<button id="relay-skip">동작 건너뛰기</button>':d.stage===6?'구매·결제·투호는 시연 · 부스와 판매가는 제안':'실제 인증·예약·결제는 발생하지 않습니다.';
  $('relay-time').innerHTML=`${icon('clock',14)} ${clockLabel(minutesAt(d))} <small>시연 시각</small>`;$('relay-mini-map').innerHTML=routeSVG(d.stage);
  $('relay-wallet-label').textContent=state.coupon==='used'?'할인권 사용 완료':state.coupon==='issued'?'체험 할인권 1장':'나의 여행 기록';
  document.querySelectorAll('[data-chapter]').forEach(b=>{const i=Number(b.dataset.chapter);b.setAttribute('aria-pressed',String(live&&relayStepIndex(i)===relayStepIndex(d.stage)));b.disabled=busy;b.onclick=()=>{if(canEnter(state,i)&&state.started){preview=null;dispatch({type:'GO',index:i});}else{preview=i;render();}scene?.resetView();};});
  app.querySelectorAll('[data-meal]').forEach(b=>b.onclick=()=>dispatch({type:'MEAL',id:b.dataset.meal}));app.querySelectorAll('[data-program]').forEach(b=>b.onclick=()=>dispatch({type:'PROGRAM',id:b.dataset.program}));app.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>dispatch({type:'COLOR',color:b.dataset.color}));app.querySelectorAll('[data-transport]').forEach(b=>b.onclick=()=>dispatch({type:'TRANSPORT',id:b.dataset.transport}));app.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>perform({type:'BUY',id:b.dataset.buy,animation:'buy'}));
  if($('relay-scan-fail'))$('relay-scan-fail').onclick=()=>perform({type:'SCAN',valid:false,animation:'scan'});
  if($('relay-transit-source'))$('relay-transit-source').onclick=showRoute;if($('relay-bridge-info'))$('relay-bridge-info').onclick=showSources;if($('relay-fountain'))$('relay-fountain').onclick=()=>{scene?.fountain();announce('분수 시연을 전환했습니다. 실제 운영 시간과는 무관합니다.');};
  if($('relay-aim'))$('relay-aim').oninput=e=>{aim=Number(e.target.value);};if($('relay-throw'))$('relay-throw').onclick=()=>perform({type:'THROW',hit:Math.abs(aim-50)<=10,animation:'game'});
  if($('relay-skip'))$('relay-skip').onclick=()=>{if(scene?.action)scene.action.elapsed=scene.action.duration;};
  const options={meal:d.meal,program:d.program,craftSteps:d.craftSteps,color:d.paintColor,maskArt:d.maskArt,transport:d.transport,cover:!live,walked:d.bridgeWalked};const id=live?c.id:'bridge';const key=JSON.stringify([id,options]);if(scene&&key!==sceneKey){scene.setScene(id,options);sceneKey=key;}
 }
 async function perform(action){if(busy||preview!==null)return;busy=true;render();let completed=true;
  if(action.type==='CRAFT'&&state.program==='mask')completed=await paintInWorld();
  else if(action.type==='EAT'||action.type==='CRAFT'||(action.type==='SCAN'&&action.valid!==false)){scene?.keys.clear();completed=await runActivity({type:action.type,program:state.program,step:state.craftSteps,color:state.paintColor,onInput:()=>scene?.act('eat')});}
  if(completed&&action.animation&&scene&&action.type!=='EAT')completed=await scene.act(action.animation,action);busy=false;if(!completed){render();return;}const before=state;state=relayReducer(state,action);persist();render();
  if(action.type==='GO')$('relay-title').focus({preventScroll:true});
  if(state!==before){const messages={EAT:'식사를 마쳤어요. 영수증을 받아 다음 체험으로 이어가세요.',SCAN:state.scanError?'인증 실패: 흐린 QR입니다. 다시 스캔할 수 있어요.':'시연 영수증 인증 완료. 체험 10% 할인권을 받았어요.',REDEEM:'할인권 사용 완료. 이제 직접 체험해보세요.',CRAFT:state.craftSteps===3?`${PROGRAMS[state.program].name} 완성! 다른 체험도 선택할 수 있어요.`:`${state.craftSteps} / 3 단계 완료`,ARRIVE:'월영교에 도착했습니다.',WALK:'월영정 산책 완료. 다음은 강변 팝업입니다.',BUY:'구매 시연을 여행 기록에 담았습니다.',THROW:action.hit?'성공! 화살이 들어갔어요.':'아쉽게 빗나갔어요. 가운데로 다시 조준해보세요.'};if(messages[action.type])announce(messages[action.type]);}
  if(state.finished)showSummary();
 }
 function showSummary(){const p=PROGRAMS[state.redeemedProgram||state.program];$('relay-summary-content').innerHTML=`<p class="relay-overline">YOUR ANDONG STORY</p><div class="finish-seal">이어<br>드림</div><h2>한 끼가,<br>하루의 추억이 되었어요.</h2><p>원도심의 식사와 체험에서 월영교의 밤까지.<br>이어드림의 세 단계를 모두 경험했습니다.</p><div class="finish-relay" aria-label="완주한 릴레이">${RELAY_STEPS.map(step=>`<span>✓ ${step.label}</span>`).join('<i>→</i>')}</div><div class="finish-route"><span>${MEALS[state.meal].name}</span> → <span>${state.completedPrograms.map(x=>PROGRAMS[x].short).join(' · ')}</span> → <span>월영교·팝업</span></div><div class="finish-stats"><div><b>${state.completedPrograms.length}</b><span>완성한 전통 체험</span></div><div><b>${money(p.examplePrice*.1)}</b><span>체험 할인 예시</span></div><div><b>${state.cart.length}</b><span>팝업 구매 시연</span></div></div><button class="relay-primary" id="relay-another">다른 전통 체험도 해보기 ${icon('arrow')}</button><a class="summary-atlas" href="?layout=journey">전체 지도에서 코스·귀가편 살펴보기 ↗</a><small>모든 이용 기록과 할인은 시연입니다. 실제 방문·매출·주민증 실적에 합산하지 않습니다.</small>`;$('relay-summary').showModal();scene?.setPaused(true);$('relay-another').onclick=()=>{$('relay-summary').close();scene?.setPaused(false);dispatch({type:'GO',index:3});};}
 $('relay-summary-close').onclick=()=>{$('relay-summary').close();scene?.setPaused(false);};$('relay-summary').addEventListener('cancel',()=>scene?.setPaused(false));
 $('relay-start').onclick=()=>{preview=null;dispatch({type:'START'});$('relay-title').focus({preventScroll:true});};
 $('relay-action').onclick=()=>{if(preview!==null){preview=null;render();return;}perform(nextAction(state));};
 document.querySelectorAll('[data-look]').forEach(b=>b.onclick=()=>scene?.look(Number(b.dataset.look)));for(const [id,direction] of [['relay-forward',1],['relay-backward',-1]]){const button=$(id);button.onpointerdown=e=>{button.setPointerCapture(e.pointerId);if(scene)scene.touchMove.forward=direction;};const stop=()=>{if(scene)scene.touchMove.forward=0;};button.onpointerup=stop;button.onpointercancel=stop;button.onkeydown=e=>{if(e.key==='Enter'||e.code==='Space')scene?.move(direction*.45);};}
 window.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&!e.repeat&&!['INPUT','SELECT','TEXTAREA','BUTTON','A','CANVAS'].includes(e.target.tagName)&&!$('relay-drawer').open&&!$('relay-summary').open&&state.started){e.preventDefault();scene?.interact();}});
 render();
 try{await document.fonts.load('500 16px Pretendard');scene=new RelayScene($('relay-world'),{onInteract:action=>{if(!state.started||preview!==null||busy)return;if(action.startsWith('talk:')){talk(action.split(':')[1]);return;}if(action==='primary')perform(nextAction(state));if(action==='buy-food')perform({type:'BUY',id:'food',animation:'buy'});if(action==='buy-craft')perform({type:'BUY',id:'craft',animation:'buy'});if(action==='game'&&state.gameAttempts<3)perform({type:'THROW',hit:Math.abs(aim-50)<=10,animation:'game'});},onFocus:focus=>{const active=state.started&&preview===null&&!busy&&focus;$('relay-interact').hidden=!active;if(active)$('relay-interact').querySelector('span').textContent=focus.action==='primary'?nextAction(state).label:focus.name;app.classList.toggle('has-interaction',!!active);},onError:announce});sceneKey='';render();}catch(error){console.error('Relay 3D unavailable',error);$('relay-world').classList.add('world-unavailable');announce('3D 화면을 열 수 없습니다. 아래 조작으로 여정은 계속 체험할 수 있습니다.');}
 window.addEventListener('pagehide',event=>{if(!event.persisted)scene?.dispose();});
}
